### ISSUE TITLE
Not compatible with .Net Core

### ISSUE THREAD

**Issue by natehast** [smartsheet-platform/smartsheet-csharp-sdk#69]
Any plans of making the SDK compatible with .Net Core to allow for cross platform development?

**Comment by seweil** [comment]
Thanks for the suggestion. Can you tell me more about your desired platform/scenario?

**Comment by jincod** [comment]
Hi @seweil 

I want to develop ASP.NET Core apps. Would be grade if SDK supports .NET Standard.

**Comment by seweil** [comment]
@jincod, please elaborate on your desired platform and scenario. 

Currently we require Mono (Xamarin) to run on anything other than Windows. And the SDK runs well on Visual Studio for the Mac.

**Comment by jincod** [comment]
@seweil 

I want to deploy ASP.NET Core application inside Docker (without Mono)

**Comment by jincod** [comment]
Hi @seweil 

I've built SS SDK for `netstandard2.0` for our project. I'm working at the separate branch https://github.com/jincod/smartsheet-csharp-sdk/tree/feature/dotnetcore-v2 (WIP). I can make a PR. Are you interested in these changes?

**Comment by timwellswa** [comment]
Hi @jincod 

That's awesome...thanks so much for your efforts on behalf of the SS SDK. It turns out I was working on the same port. I will compare with your branch, take the best from both and get it merged at some point in the near future. I have a couple other things brewing though so it will be a few weeks.

Thanks again...really appreciated.

**Comment by Craigfis** [comment]
Any update on that efffort, Tim? It seems a few weeks (and more) have passed. :-)

**Comment by mattgwagner** [comment]
Ran into this as well, still nothing updated?

**Comment by jamesmh** [comment]
An SDK supporting .NET Standard 2.0+ would be fantastic. Kinda a deal breaker right now 😥

Since the current SDK targets .NET Framework it's kinda out of the question for me.

Integration with the .NET Core DI system, asynchronous `Task` based Http calls, etc. would be necessary for needs (and those are pretty standard expectations of any .NET Core lib anyways).

Thanks!

**Comment by etfrenchvcu** [comment]
@timwellswa Do you have any estimate when .NET Core compatibility will be introduced?

**Comment by MarkIannucci** [comment]
Has anyone attempted to use the SDK after #101 went in yesterday?

**Comment by timwellswa** [comment]
I have not published a new nuget.org package. @MarkIannucci why, what's up?

**Comment by timwellswa** [comment]
The Nuget package containing netstandard2.0 and net452 is now published on Nuget.org. @MarkIannucci @etfrenchvcu @natehast @jamesmh @mattgwagner @Craigfis @jincod (and anyone else I might have forgotten!) would really appreciate if you could take a look and let me know if it looks like anything is missing. Thanks!

**Comment by mattgwagner** [comment]
@timwellswa tried it out today and things look to be working.

**Comment by MarkIannucci** [comment]
@timwellswa , we've been using version 2.68.2 in our .Net Core app and it has been working well also.  Thanks!
